In [3]:
import numpy as np
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
vector = np.arange(0,10)

In [7]:
vector.ndim

1

In [14]:
# crear un dataframe
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [1, 2, 3, 4, 5]
})
df

A  B  C
0  1  5  1
1  2  4  2
2  3  3  3
3  4  2  4
4  5  1  5

In [15]:
df.shape

(5, 3)

In [16]:
df.drop_duplicates()

A  B  C
0  1  5  1
1  2  4  2
2  3  3  3
3  4  2  4
4  5  1  5

In [32]:
df.loc[0:2,['A','B']]

A  B
0  1  5
1  2  4
2  3  3

In [21]:
df.describe()

A         B         C
count  5.000000  5.000000  5.000000
mean   3.000000  3.000000  3.000000
std    1.581139  1.581139  1.581139
min    1.000000  1.000000  1.000000
25%    2.000000  2.000000  2.000000
50%    3.000000  3.000000  3.000000
75%    4.000000  4.000000  4.000000
max    5.000000  5.000000  5.000000

In [22]:
arr = np.array([13, 6, 3, 5, 10])
np.argmax(arr) # devuelve el índice del valor máximo 

0

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [30]:
arr = np.array([[7,8],[2,1], [2,4]])
arr.shape

(3, 2)

In [31]:
np.array(['hola','2','4','5'],dtype='float64')

ValueError: could not convert string to float: 'hola'