In [ ]:
# !pip install --upgrade pandas

     |████████████████████████████████| 9.5MB 2.6MB/s 
  Found existing installation: pandas 1.1.2
    Uninstalling pandas-1.1.2:
      Successfully uninstalled pandas-1.1.2


In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.4'

In [2]:
# para que los numeros tengan dos cifras decimales
pd.options.display.float_format = '{:.2f}'.format

In [4]:
# para que los numeros tengan dos cifras decimales en numpý
np.set_printoptions(precision=1)

## Concatenacion en numpy

In [5]:
x1 = np.random.rand(2,5)*10
x1

array([[0. , 4.3, 9.6, 9.5, 8.4],
       [9.7, 9.5, 1.1, 8.6, 2. ]])

In [6]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.7, -0.9, -0. , -0.9, -0.3],
       [-0.8, -0.6, -1. , -0.5, -0.3]])

In [8]:
#concatenar arrays por filas
np.concatenate([x1,x2])

array([[ 0. ,  4.3,  9.6,  9.5,  8.4],
       [ 9.7,  9.5,  1.1,  8.6,  2. ],
       [-0.7, -0.9, -0. , -0.9, -0.3],
       [-0.8, -0.6, -1. , -0.5, -0.3]])

In [9]:
np.concatenate([x1,x2]).shape

(4, 5)

In [10]:
# concatenar arrays por columnas
np.concatenate([x1,x2], axis = 1)

array([[ 0. ,  4.3,  9.6,  9.5,  8.4, -0.7, -0.9, -0. , -0.9, -0.3],
       [ 9.7,  9.5,  1.1,  8.6,  2. , -0.8, -0.6, -1. , -0.5, -0.3]])

In [11]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

## Concatenacion con Series

In [12]:
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   0.01
b   4.25
c   9.57
d   9.53
e   8.44
dtype: float64

In [14]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.72
d   -0.89
e   -0.05
f   -0.94
g   -0.34
dtype: float64

In [15]:
#concatenar a lo largo de las filas con el index
pd.concat([s1,s2], axis=1)

0     1
a 0.01   NaN
b 4.25   NaN
c 9.57 -0.72
d 9.53 -0.89
e 8.44 -0.05
f  NaN -0.94
g  NaN -0.34

In [16]:
s1.reset_index(drop=True)

0   0.01
1   4.25
2   9.57
3   9.53
4   8.44
dtype: float64

In [18]:
#concatenar a lo largo de las columnas sin un index
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 0.01 -0.72
1 4.25 -0.89
2 9.57 -0.05
3 9.53 -0.94
4 8.44 -0.34

## Concatenar Dataframes

In [19]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 3.52 7.47
1 2.95 4.50
2 5.18 5.06

In [20]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.99 -0.71
3 -0.16 -0.67
4 -0.60 -0.78

In [22]:
#concatenar a lo largo de las filas
pd.concat([df1,df2])

a     b
0  3.52  7.47
1  2.95  4.50
2  5.18  5.06
2 -0.99 -0.71
3 -0.16 -0.67
4 -0.60 -0.78

In [24]:
#concatenar a lo largo de las columnas
pd.concat([df1,df2], axis=1)

a    b     a     b
0 3.52 7.47   NaN   NaN
1 2.95 4.50   NaN   NaN
2 5.18 5.06 -0.99 -0.71
3  NaN  NaN -0.16 -0.67
4  NaN  NaN -0.60 -0.78

In [25]:
#concatenar los indices que compartes ambos
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 5.18 5.06 -0.99 -0.71

In [27]:
#concatenar sin respetar los indices
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 3.52 7.47 -0.99 -0.71
1 2.95 4.50 -0.16 -0.67
2 5.18 5.06 -0.60 -0.78

In [28]:
#concatenar agregando
df1.append(df2).append(df2)

a     b
0  3.52  7.47
1  2.95  4.50
2  5.18  5.06
2 -0.99 -0.71
3 -0.16 -0.67
4 -0.60 -0.78
2 -0.99 -0.71
3 -0.16 -0.67
4 -0.60 -0.78

In [30]:
#transponer un dataframe
df1.T

0    1    2
a 3.52 2.95 5.18
b 7.47 4.50 5.06

In [31]:
df1.T.append(df2.T).T

a    b     a     b
0 3.52 7.47   NaN   NaN
1 2.95 4.50   NaN   NaN
2 5.18 5.06 -0.99 -0.71
3  NaN  NaN -0.16 -0.67
4  NaN  NaN -0.60 -0.78