# Primeros pasos con Google Colab: configuración del entorno de trabajo


In [ ]:
x = 12
x

12

In [ ]:
y = 4

In [ ]:
x + y 

16

In [ ]:
x = "joel"
y = "barrantes"
x + y

'joelbarrantes'

In [ ]:
x + " " + y

'joel barrantes'

In [ ]:
[1,2,3,4,5] + [2,3,4]

[1, 2, 3, 4, 5, 2, 3, 4]

In [ ]:
lista = [1,2,3,4,5]

In [ ]:
lista[0]

1

In [ ]:
lista[4]

5

In [ ]:
lista[-1]

5

In [ ]:
import numpy as np

In [ ]:
vector = np.array([1,2,3,4,5])

In [ ]:
vector + 10

array([11, 12, 13, 14, 15])

In [ ]:
vector.shape

(5,)

In [ ]:
vector_2 = np.array([[1,2,3,4],[2,3,4,5]])

In [ ]:
vector_2[0]

array([1, 2, 3, 4])

In [ ]:
vector_2[0][-1]

4

# Series e Indexación y selección de datos

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,9,8,7])

0    10
1     9
2     8
3     7
dtype: int64

In [ ]:
serie = pd.Series([10,9,8,7,6,4,3,5,4,3,2])

In [ ]:
serie.values

array([10,  9,  8,  7,  6,  4,  3,  5,  4,  3,  2])

In [ ]:
serie.index

RangeIndex(start=0, stop=11, step=1)

In [ ]:
serie.shape

(11,)

In [ ]:
serie[2]

8

In [ ]:
serie[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [ ]:
serie = pd.Series([10,9,8,7,6], index=['a','b','c','d','e'])

In [ ]:
serie

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
serie[['b','c','e']]

b    9
c    8
e    6
dtype: int64

In [ ]:
serie['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

### Diccionarios

In [ ]:
dict_data = {'CO': 100, 'MX': 200, 'AR': 300}

In [ ]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
for i in dict_data.keys():
    print(dict_data[i])


100
200
300


In [ ]:
dict_data['CO']

100

In [ ]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [ ]:
pd.Series(dict_data, index=['CO', 'MX', 'PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
np.nan

nan

In [ ]:
np.nan + 10

nan

In [ ]:
np.nan * 10

nan

### Crear Series

In [ ]:
serie = pd.Series(dict_data, index=['CO', 'MX', 'PE'])

In [ ]:
serie.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [ ]:
serie.notnull()

CO     True
MX     True
PE    False
dtype: bool

#### Valores nulos
Existen diverso métodos para trabajar con datos nulos:

* serie.isnull().sum() -> número total de valores nulos
* serie.fillna(<valor>) -> rellena los valores nulos con el valor dado (string/float)
* serie.dropna() -> borra todos los registros con al menos un valor nulo
* serie.ffill() -> rellena el valor nulo con el mismo valor de la fila anterior
* serie.backfill() -> rellena el valor nulo con el mismo valor de la fila siguiente
.